# Generated by Django 3.0.6 on 2020-05-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('balance', models.IntegerField()),
                ('updateCW', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.CharField(max_length=60)),
                ('frequency', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrents', to='cash.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.CharField(max_length=60)),
                ('week', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='cash.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.CharField(max_length=60)),
                ('week', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='cash.Account')),
                ('planStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='cash.PlanStatus')),
                ('typeStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='cash.TypeStatus')),
            ],
        ),
    ]
